; PlatformIO Project Configuration File

[platformio]
default_envs = release, debug

[env]
    platform = https://github.com/Jason2866/platform-espressif32.git#Arduino/IDF5
    platform_packages = 
        platformio/framework-arduinoespressif32 @ symlink://../.platformio/packages/framework-arduinoespressif32
    monitor_speed = 115200
    monitor_raw = true
    
    lib_deps = 
        rover_can_lib=symlink://../lib/rover_can2
        lib_rover=symlink://../lib/rover_lib2

    build_unflags =
        -std=gnu++11
        -Wno-maybe-uninitialized
        -Wno-unused-function
        -Wno-unused-but-set-variable
        -Wno-unused-variable
        -Wno-deprecated-declarations
        -Wno-unused-parameter
        -Wno-sign-compare

    build_flags =
        -Ilib
        -Isrc
        -std=c++23
        -Wall
        -Wextra
        -D CONFIG_LOG_DEFAULT_LEVEL_ERROR

    [env:release]
        board = esp32-s3-devkitc-1
        framework = arduino
        build_type = release
        board_upload.after_reset = watchdog_reset
        build_flags = 
            ${env.build_flags}
            -D RELEASE
            -D ARDUINO_USB_CDC_ON_BOOT
            -D ARDUINO_USB_MODE
            -g03

    [env:debug]
        board = esp32-s3-devkitc-1
        framework = arduino
        build_type = debug
        build_unflags = 
            ${env.build_unflags}

        build_flags = 
            ${env.build_flags}
            -D DEBUG
            -D ARDUINO_USB_CDC_ON_BOOT
            -D ARDUINO_USB_MODE
            -D VERBOSE
            -D GLOBAL_SEVERITY_LEVEL=Logger::eSeverityLevels::DEBUG_
            -D NODE_BYPASS_SEVERITY_LEVEL=Logger::eSeverityLevels::WARN
            -g03

    [env:test_off_device]
        platform = native
        test_framework = googletest
        build_type = debug
        debug_build_flags = -O0 -g -ggdb
        debug_test = *
        lib_deps = 
            ${env.lib_deps}
            google/googletest
        build_flags = 
            ${env.build_flags}
            -D TEST_NATIVE
            -D VERBOSE
